### ISSUE TITLE
need readme.md or documentation

### ISSUE THREAD

**Issue by jackytank** [nihadenes/AsciCam#1]
Hi, I'm new to Python programming and want to try out your code but It doesn't have any documentation or guide, please consider making a README.MD so that we can better use your project, thank you

**Comment by nihadenes** [comment]
For sure!, can you too tell me about the problems you faced?

**Comment by jackytank** [comment]
Oh I just a new Python programmer, it would be nice if you do a guide on how to use this script to create ASCII art by webcam
